# Generated by Django 3.0.3 on 2021-04-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус опроса'),
        ),
    ]
