# Generated by Django 3.0.3 on 2021-04-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey_api', '0003_auto_20210422_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='got_answer',
            field=models.BooleanField(default=False, verbose_name='Пройден'),
        ),
    ]
